const routes = {
  home: "/",
  following: "/following",
  shop: "/shop",
  profile: "/profile/:profile_id",
  // profile: "/profile",
  upload: "/upload",
  search: "/search",
  login: "/login",
  register: "/register",
  forgetPass: "/reset_password",

  productdetail: "/product/:product_id",
  cart: "/cart",
  test: "/test",
  check_out: "/check_out",
  payment: "/payment",
  invoice: "/invoice",
  invoice_id: "/invoice/:invoice_id",
  location: "/location",
  admin: "/admin",
  adminLogin: "/admin/login",
  adminUser: "/admin/user",
  adminUserDetail: "/admin/user/:user_id",
  adminProduct: "/admin/product",
  adminProductDetail: "/admin/product/:id_color",
  adminProductEdit: "/admin/product/edit",
  adminProductAdd: "/admin/product/add",
  adminInvoice: "/admin/invoice",
  adminInvoiceDetail: "/admin/invoice/:invoice_id",
};

export default routes;
